# Generated by Django 6.0.2 on 2026-04-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_feedback_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_new_followers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_post_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_report_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_staff_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme_preference',
            field=models.CharField(choices=[('system', 'Use system appearance'), ('light', 'Always use light mode'), ('dark', 'Always use dark mode')], default='system', max_length=12),
        ),
    ]
