# Generated by Django 6.0.2 on 2026-04-13 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_authorfollow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='postreaction',
            name='guest_token',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='postreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'blog', 'reaction_type'), name='unique_user_post_reaction'),
        ),
        migrations.AddConstraint(
            model_name='postreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('guest_token', ''), _negated=True)), fields=('guest_token', 'blog', 'reaction_type'), name='unique_guest_post_reaction'),
        ),
    ]
