# Generated by Django 6.0.2 on 2026-04-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_postreaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(upload_to='posts/featured/%Y/%m/%d'),
        ),
    ]
